# Generated by Django 5.2.4 on 2025-08-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_domaincv_cv_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionJobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.domaincv')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingScore2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('correspend', models.TextField(blank=True, null=True)),
                ('manque', models.TextField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.cv')),
                ('job_offer_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.descriptionjoboffer')),
            ],
            options={
                'unique_together': {('job_offer_desc', 'cv')},
            },
        ),
    ]
